name: Build, Release, and Prepare EXE

permissions:
  contents: write
on:
  push:
    tags:
      - 'v*'   # Triggers on tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow imageio numpy requests keyboard

      - name: Clean exe (runtime here) folder
        shell: cmd
        run: |
          if exist "exe (runtime here)" (
            del /q /f "exe (runtime here)\*"
            for /d %%i in ("exe (runtime here)\*") do rmdir /s /q "%%i"
          ) else (
            mkdir "exe (runtime here)"
          )

      - name: Build EXE with PyInstaller
        run: |
          pyinstaller --onefile --name "ControlledMatrix" --icon=static\Logo.ico --distpath "exe (runtime here)" "Source code/main.py"

      - name: Set up Git LFS
        run: |
          git lfs install
          git lfs track "*.exe"
          git lfs track "*.scr"
          git add .gitattributes

      - name: Copy EXE as SCR
        run: |
          copy "exe (runtime here)\ControlledMatrix.exe" "exe (runtime here)\ControlledMatrix.scr"

      - name: Checkout main branch
        run: |
          git fetch origin main
          git checkout main

            - name: Remove old files from exe (runtime here) in repo
      - run: |
          git fetch origin main
          git checkout main
          if exist "exe (runtime here)" (
            del /q /f "exe (runtime here)\*"
            for /d %%i in ("exe (runtime here)\*") do rmdir /s /q "%%i"
          )
          git rm -rf "exe (runtime here)" || echo "Nothing to remove"
          git commit -am "Automated: Clean exe (runtime here) folder before build [skip ci]" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        shell: cmd